# Generated by Django 5.1.2 on 2024-10-10 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                (
                    "event_create_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Event Created At",
                    ),
                ),
                (
                    "start_date_event",
                    models.DateTimeField(verbose_name="Event Start Date"),
                ),
                (
                    "end_date_event",
                    models.DateTimeField(blank=True, verbose_name="Event End Date"),
                ),
                (
                    "start_date_register",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Registration Start Date",
                    ),
                ),
                (
                    "end_date_register",
                    models.DateTimeField(verbose_name="Registration End Date"),
                ),
                ("description", models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Attendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organizer_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "event_list",
                    models.ManyToManyField(related_name="events", to="api.event"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date registered",
                    ),
                ),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.attendee"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.event"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attendee",
            name="event_list",
            field=models.ManyToManyField(through="api.Ticket", to="api.event"),
        ),
    ]
