# Generated by Django 5.1.2 on 2024-10-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="dress_code",
            field=models.CharField(
                choices=[
                    ("CASUAL", "Casual"),
                    ("SMART_CASUAL", "Smart Casual"),
                    ("BUSINESS_CASUAL", "Business Casual"),
                    ("SEMI_FORMAL", "Semi-Formal"),
                    ("FORMAL", "Formal"),
                    ("BLACK_TIE", "Black Tie"),
                    ("WHITE_TIE", "White Tie"),
                    ("THEMED", "Themed Dress Code"),
                    ("OUTDOOR_BEACH_CASUAL", "Outdoor/Beach Casual"),
                ],
                default=" ",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="status_registeration",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("FULL", "Full"),
                    ("PENDING", "Pending"),
                    ("CANCELLED", "Cancelled"),
                    ("WAITLIST", "Waitlist"),
                ],
                default=" ",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
