# Generated by Django 5.1.2 on 2024-10-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeuser",
            name="address",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendeeuser",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendeeuser",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(default="kasetsart", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="longtitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
