# Generated by Django 5.1.2 on 2024-10-10 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='event_list',
        ),
        migrations.AddField(
            model_name='event',
            name='max_attendee',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.organizer'),
            preserve_default=False,
        ),
    ]
