# Generated by Django 5.1.2 on 2024-10-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_attendeeuser_address_attendeeuser_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendeeuser",
            name="longitude",
        ),
        migrations.AddField(
            model_name="attendeeuser",
            name="longtitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendeeuser",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="attendeeuser",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
