# Generated by Django 5.1.2 on 2024-10-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_attendeeuser_alter_organizer_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeuser",
            name="last_name",
            field=models.CharField(default="gan", max_length=100),
            preserve_default=False,
        ),
    ]
